name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
    
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Build web assets
      run: npm run build
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
    
    - name: Add Android platform
      run: npx cap add android
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
    
    - name: Build debug APK
      working-directory: android
      run: ./gradlew assembleDebug --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: besmi-android-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
